Repository sopt-makers/sopt.org-backend, pull requests merged in 2023-03, with the labels that each got.

#30 Chore/environment setting
  .github/workflows/cd.develop.yml
  .github/workflows/ci.deploy.yml
  .gitignore
  docker-compose/docker-compose.yml
  dockerfile
  package.json
  src/app.controller.spec.ts
  src/utils/constants.ts
  yarn.lock
Labels: size/XL

#32 Docs/review api interface
  docs/review/review.swagger.ts
  package.json
  src/reviews/controllers/reviews.controller.ts
  src/reviews/dtos/reviews-request.dto.ts
  src/reviews/dtos/reviews-response.dto.ts
  src/reviews/entities/reviews.entity.ts
  src/utils/paginate-request.dto.ts
  src/utils/paginate-response.dto.ts
  test/utils/paginate.response.dto.spec.ts
  yarn.lock
Labels: size/XXL

#33 Merge : develop -> feat/review
  docs/review/review.swagger.ts
  package.json
  src/reviews/controllers/reviews.controller.ts
  src/reviews/dtos/reviews-request.dto.ts
  src/reviews/dtos/reviews-response.dto.ts
  src/reviews/entities/reviews.entity.ts
  src/utils/paginate-request.dto.ts
  src/utils/paginate-response.dto.ts
  test/utils/paginate.response.dto.spec.ts
  yarn.lock
Labels: size/XXL

#34 Feat/review
  package-lock.json
  package.json
  src/reviews/controllers/reviews.controller.ts
  src/reviews/services/reviews.service.ts
  src/utils/paginate-request.dto.ts
  yarn.lock
Labels: size/XXL

#36 Refactor/reviews
  src/configs/typeorm.config.ts
  src/reviews/controllers/reviews.controller.ts
  src/reviews/services/reviews.service.ts
Labels: size/M

#38 Feat/random review
  docs/review/review.swagger.ts
  src/configs/typeorm.config.ts
  src/reviews/controllers/reviews.controller.ts
  src/reviews/dtos/reviews-response.dto.ts
  src/reviews/services/reviews.service.ts
Labels: size/M

#39 Develop
  .github/workflows/cd.develop.yml
  .github/workflows/cd.prod.yml
  .github/workflows/ci.deploy.yml
  .gitignore
  docker-compose/doc/doc-filelist.js
  docker-compose/doc/doc-script.js
  docker-compose/doc/doc-style.css
  docker-compose/docker-compose.yml
  dockerfile
  docs/review/review.swagger.ts
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.module.ts
  src/configs/typeorm.config.ts
  src/reviews/controllers/reviews.controller.ts
  src/reviews/dtos/reviews-request.dto.ts
  src/reviews/dtos/reviews-response.dto.ts
  src/reviews/entities/reviews.entity.ts
  src/reviews/reviews.module.ts
  src/reviews/services/reviews.service.ts
  src/utils/constants.ts
  src/utils/paginate-request.dto.ts
  src/utils/paginate-response.dto.ts
  test/utils/paginate.response.dto.spec.ts
  yarn.lock
Labels: size/XXL

#40 FIX 아티클 중복 제거
  src/reviews/services/reviews.service.ts
Labels: size/XS

#41 FIX 아티클 중복 제거-1
  src/reviews/services/reviews.service.ts
Labels: size/XS

#42 Refactor/projects api
  docs/projects/projects.swagger.ts
  src/configs/env.config.ts
  src/configs/typeorm.config.ts
  src/projects/controllers/projects.controller.ts
  src/projects/dtos/playground-project-detail-response.dto.ts
  src/projects/dtos/playground-project-response.dto.ts
  src/projects/dtos/project-detail-response.dto.ts
  src/projects/dtos/projects-list-response.dto.ts
  src/projects/dtos/projects-response.dto.ts
  src/projects/projects.module.ts
  src/projects/services/projects.service.ts
  src/utils/compare.ts
  src/utils/constants.ts
Labels: size/L
