Repository sopt-makers/sopt.org-backend, pull requests merged in 2023-05, with the labels that each got.

#54 Feat/about sopt query
  docs/aboutsopt/aboutSopt.swagger.ts
  src/aboutsopt/controllers/aboutsopt.controller.ts
  src/aboutsopt/services/aboutsopt.service.ts
Labels: size/M

#56 Refactor/about sopt
  docs/aboutsopt/aboutSopt.swagger.ts
  docs/members/member.swagger.ts
  docs/study/study.swagger.ts
  src/aboutsopt/aboutsopt.module.ts
  src/aboutsopt/controllers/aboutsopt.controller.ts
  src/aboutsopt/dtos/get-about-sopt-response.dto.ts
  src/aboutsopt/services/aboutsopt.service.ts
  src/app.module.ts
  src/members/controller/members.controller.ts
  src/members/dtos/member-request.dto.ts
  src/members/dtos/member-response-dto.ts
  src/members/dtos/member-response.dto.ts
  src/members/memberModule.ts
  src/members/service/member.service.ts
  src/projects/controllers/projects.controller.ts
  src/projects/projectModule.ts
  src/projects/services/project.service.ts
  src/study/controller/study.controller.ts
  src/study/dtos/crew-study-response.dto.ts
  src/study/dtos/study-response.dto.ts
  src/study/service/study.service.ts
  src/study/study.module.ts
Labels: size/XL

#55 Fix/publish about sopt
  package.json
  src/aboutsopt/services/aboutsopt.service.ts
  yarn.lock
Labels: size/M

#58 Fix/about sopt
  docs/aboutsopt/aboutSopt.swagger.ts
  src/aboutsopt/controllers/aboutsopt.controller.ts
  src/aboutsopt/dtos/get-about-sopt-response.dto.ts
  src/aboutsopt/services/aboutsopt.service.ts
  src/study/service/study.service.ts
Labels: size/M

#59 refactor: api semester => generation으로모두 변경
  src/aboutsopt/controllers/aboutsopt.controller.ts
Labels: size/XS

#61 Feat/sopticle
  docs/sopticle/sopticle.swagger.ts
  src/app.module.ts
  src/auth/auth-playground.guard.ts
  src/auth/auth.module.ts
  src/common/decorator/current-user.decorator.ts
  src/common/type.ts
  src/internal/internalService.module.ts
  src/internal/playground/dto/get-playground-user-info-response.dto.ts
  src/internal/playground/playgroud.module.ts
  src/internal/playground/playground.repository.ts
  src/internal/playground/playground.service.ts
  src/reviews/dtos/reviews-request.dto.ts
  src/reviews/dtos/reviews-response.dto.ts
  src/reviews/entities/reviews.entity.ts
  src/reviews/services/reviews.service.ts
  src/sopticle/controllers/sopticle.controller.ts
  src/sopticle/dtos/create-sopticle.dto.ts
  src/sopticle/dtos/get-sopticle-list-request.dto.ts
  src/sopticle/dtos/sopticle-response.dto.ts
  src/sopticle/entities/sopticle.entity.ts
  src/sopticle/entities/sopticleLike.entity.ts
  src/sopticle/services/sopticle.service.ts
  src/sopticle/sopticle.module.ts
Labels: size/L

#62 fix: member enum
  src/projects/dtos/playground-member.ts
  src/projects/services/project.service.ts
Labels: size/S

#60 Refactor/study
  src/aboutsopt/dtos/get-about-sopt-response.dto.ts
  src/aboutsopt/services/aboutsopt.service.ts
  src/common/cache/cache.module.ts
  src/common/type.ts
  src/study/controller/study.controller.ts
  src/study/dtos/crew-study-response.dto.ts
  src/study/repository/study.repository.ts
  src/study/service/study.service.spec.ts
  src/study/service/study.service.ts
  src/study/study.module.ts
Labels: size/L

#63 fix: add TL to member role
  src/projects/dtos/playground-member.ts
Labels: size/XS

#64 Feat/scrap service
  docs/sopticle/sopticle.swagger.ts
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/common/type.ts
  src/internal/playground/dto/get-playground-sopticle-response.dto.ts
  src/internal/playground/playground.repository.ts
  src/internal/playground/playground.service.ts
  src/main.ts
  src/scraper/dto/create-scraper-response.dto.ts
  src/scraper/puppeteer.service.ts
  src/scraper/scraper.module.ts
  src/scraper/scraper.service.ts
  src/scraper/scraping-strategy-factory.service.ts
  src/scraper/strategy/brunch-strategy.scraping.strategy.ts
  src/scraper/strategy/scrap.strategy.ts
  src/scraper/strategy/tisotry-scraping.strategy.ts
  src/scraper/strategy/velog-scraping.strategy.ts
  src/sopticle/controllers/sopticle.controller.ts
  src/sopticle/dtos/create-sopticle.dto.ts
  src/sopticle/dtos/like-sopticle-response.dto.ts
  src/sopticle/dtos/sopticle-response.dto.ts
  src/sopticle/entities/sopticle.entity.ts
  src/sopticle/entities/sopticleLike.entity.ts
  src/sopticle/services/sopticle-factory.service.ts
  src/sopticle/services/sopticle.service.ts
  src/sopticle/sopticle.module.ts
  test/sopticle/dtos/IsValidateSopticlePlatformUrl.spec.ts
  yarn.lock
Labels: size/XXL

#66 Fix/puppeteer down
  package.json
  src/app.module.ts
  src/sopticle/services/sopticle.service.ts
  src/sopticle/sopticle.module.ts
  yarn.lock
Labels: size/L
