Repository sopt-makers/sopt.org-backend, pull requests merged in 2023-04, with the labels that each got.

#43 Develop merge
  docs/projects/projects.swagger.ts
  src/configs/env.config.ts
  src/configs/typeorm.config.ts
  src/projects/controllers/projects.controller.ts
  src/projects/dtos/playground-project-detail-response.dto.ts
  src/projects/dtos/playground-project-response.dto.ts
  src/projects/dtos/project-detail-response.dto.ts
  src/projects/dtos/projects-list-response.dto.ts
  src/projects/dtos/projects-response.dto.ts
  src/projects/projects.module.ts
  src/projects/services/projects.service.ts
  src/utils/compare.ts
  src/utils/constants.ts
Labels: size/L

#45 Feat/aws s3 module
  .env.sample
  docs/file/file.swagger.ts
  package.json
  src/app.module.ts
  src/aws/aws.module.ts
  src/aws/services/storage.service.ts
  src/configs/env.config.ts
  src/file/controllers/file.controller.ts
  src/file/file.module.ts
  src/file/services/file.service.ts
  yarn.lock
Labels: size/XXL

#46 Feat/about
  .env.sample
  docs/aboutsopt/aboutSopt.swagger.ts
  docs/file/file.swagger.ts
  package.json
  src/aboutsopt/aboutsopt.module.ts
  src/aboutsopt/controllers/aboutsopt.controller.ts
  src/aboutsopt/dtos/aboutsopt-post.dto.ts
  src/aboutsopt/dtos/aboutsopt-response.dto.ts
  src/aboutsopt/dtos/aboutsopt-update.dto.ts
  src/aboutsopt/entities/aboutsopt.entity.ts
  src/aboutsopt/entities/coreValue.entity.ts
  src/aboutsopt/services/aboutsopt.service.ts
  src/app.module.ts
  src/aws/aws.module.ts
  src/aws/services/storage.service.ts
  src/common/decorator/is-boolean.decorator.ts
  src/configs/env.config.ts
  src/configs/typeorm.config.ts
  src/file/controllers/file.controller.ts
  src/file/file.module.ts
  src/file/services/file.service.ts
  src/members/controller/members.controller.ts
  src/members/dtos/member-response-dto.ts
  src/members/members.module.ts
  src/members/service/members.service.ts
  src/study/controller/study.controller.ts
  src/study/dtos/study-response.dto.ts
  src/study/service/study.service.ts
  src/study/study.module.ts
  yarn.lock
Labels: size/XXL

#48 Feat/about
  .env.sample
  docs/aboutsopt/aboutSopt.swagger.ts
  src/aboutsopt/aboutsopt.module.ts
  src/aboutsopt/controllers/aboutsopt.controller.ts
  src/aboutsopt/dtos/aboutsopt-post.dto.ts
  src/aboutsopt/dtos/aboutsopt-response.dto.ts
  src/aboutsopt/dtos/aboutsopt-update.dto.ts
  src/aboutsopt/entities/aboutsopt.entity.ts
  src/aboutsopt/entities/coreValue.entity.ts
  src/aboutsopt/services/aboutsopt.service.ts
  src/app.module.ts
  src/common/decorator/is-boolean.decorator.ts
  src/configs/env.config.ts
  src/members/controller/members.controller.ts
  src/members/dtos/member-response-dto.ts
  src/members/members.module.ts
  src/members/service/members.service.ts
  src/study/controller/study.controller.ts
  src/study/dtos/study-response.dto.ts
  src/study/service/study.service.ts
  src/study/study.module.ts
Labels: size/XL

#49 Feat/about publish
  docs/aboutsopt/aboutSopt.swagger.ts
  docs/members/member.swagger.ts
  docs/study/study.swagger.ts
  src/aboutsopt/controllers/aboutsopt.controller.ts
  src/aboutsopt/services/aboutsopt.service.ts
  src/members/controller/members.controller.ts
  src/study/controller/study.controller.ts
Labels: size/L

#51 feat: add title field
  src/aboutsopt/dtos/aboutsopt-response.dto.ts
  src/aboutsopt/dtos/aboutsopt-update.dto.ts
  src/aboutsopt/entities/aboutsopt.entity.ts
Labels: size/S

#52 Feat/auth
  .env.sample
  docs/file/file.swagger.ts
  package.json
  src/aboutsopt/controllers/aboutsopt.controller.ts
  src/aboutsopt/entities/aboutsopt.entity.ts
  src/aboutsopt/services/aboutsopt.service.ts
  src/app.module.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/configs/env.config.ts
  src/configs/swagger.config.ts
  src/file/controllers/file.controller.ts
  yarn.lock
Labels: size/L
